### ISSUE TITLE
Upload File without data

### ISSUE THREAD

**Issue by gorlik1337** [remisa-yousefvand/virustotal-api#1]
```
var filename='temp//file.exe'
var name = 'file..exe'

const buffer = fs.readFileSync('temp\\'+filename)
    virusTotal.fileScan(buffer, name)
      .then((response) => {
        let resource = response.resource
        // sometime later try:
        virusTotal.fileReport(resource)
          .then((result) => {
            console.log(result.positives+'/'+ result.total)
            console.log('===============')
            console.log(result)
          })
      })
```

When i use this code to virustotal was upload blank file without data https://www.virustotal.com/pl/file/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855/analysis/1538076386/

**Comment by remisa-yousefvand** [comment]
My guess is `buffer` is empty (either file doesn't exist or your antivirus blocked access to it).
```
...
const buffer = fs.readFileSync('temp\\'+filename)
    console.log(buffer.byteLength)
    virusTotal.fileScan(buffer, name)
...
```
You don't handle errors and without enough data it is hard to say anything.
I have updated documentation and validate data in `fileScan` now.

**Comment by gorlik1337** [comment]
Sorry my bad - it was night and I'm brain death. The problem was be asynchronous working of function. File start download but in next step was readed and successful was loaded only small piece.
